### ISSUE TITLE
Do not assume default region is called "DEFAULT"

### ISSUE THREAD

**Issue by shabiel** [shabiel/Kernel-GTM#12]
Affects various routines that call out to GT.M for information. Targeted changes for the next release.

**Comment by frederickmarshall** [comment]
Thanks for adding this issue, Sam. I'm still learning my way around Github. I expect to have the initial code changes done today. After that, I'll update the unit tests for this routine to handle the new routine structure (I split out the various ACTJ strategies into their own subroutines to aid testing) and will run some timing to compare the various strategies while Linda has her evil way with my "finished" code. Once I finish fixing the various issues she manages to reveal, we'll send a pull request so you can see what you think of it.
